### ISSUE TITLE
question about code   AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by YongXu2020** [JakobKrzyston/Complex_Convolutions#2]
Traceback (most recent call last):
  File "C:\Users\###\Desktop\Complex_Convolutions-master\Complex_Convolutions-master\Complex_Convolutions\run.py", line 112, in <module>
    train_models.train(model, model_name, X_train1, X_test1, Y_train1, Y_test1, tag, load_weights, epochs=100, batch_size = 1024)
  File "C:\Users\###\Desktop\Complex_Convolutions-master\Complex_Convolutions-master\Complex_Convolutions\train_models.py", line 37, in train
    history = model.fit(X_train1,
  File "C:\Users\###\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\####\anaconda3\lib\site-packages\keras\engine\data_adapter.py", line 1418, in _make_class_weight_map_fn
    class_ids = list(sorted(class_weight.keys()))
AttributeError: 'str' object has no attribute 'keys'

**Comment by JakobKrzyston** [comment]
Hello!

This error may stem from TensorFlow and Keras having been updated since the code was written. Please use an environment with the following versions of Keras and TensorFlow:

- Keras: 2.3.0
- TensorFlow: 1.15.0

Hope that works!
